//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberEats_RespAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineCart
    {
        public int Id { get; set; }
        public int ProductID { get; set; }
        public int CustID { get; set; }
        public decimal TotAmt { get; set; }
        public int Quality { get; set; }
        public int RestID { get; set; }
        public string address { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
